Workaround for error I don't understand
Without this we get:

    MethodError: no method matching gens_2_prime_divisors(::Vector{Any})
    The function `gens_2_prime_divisors` exists, but no method is defined for this combination of argument types.

    Closest candidates are:
      gens_2_prime_divisors(::Vector{<:RingElem})
       @ Oscar .../Oscar.jl/experimental/MatroidRealizationSpaces/src/realization_space.jl:450

    Stacktrace:
     [1] n_new_Sgens(x::QQMPolyRingElem, t::AbstractAlgebra.Generic.FracFieldElem{QQMPolyRingElem}, Sgens::Vector{RingElem}, R::QQMPolyRing, xs::Vector{QQMPolyRingElem})
       @ Oscar .../Oscar.jl/experimental/MatroidRealizationSpaces/src/realization_space.jl:677

So it seems that

    unique!([sub_v(x, t, f, R, xs) for f in Sgens])

used to return a `Vector{<:RingElem}` but no more. We work around this
by forcing it to be a `Vector{RingElem}` which isn't great but
at least it works.

But why has this really stopped working?!