Replace GAP variable `_Vector_nf_elem` in Julia
It turns out that using `Oscar.eval` in our GAP code like this causes problems
when trying to use `Oscar` from within other Julia packages:

    [ Info: Precompiling test [e4ec5996-89d2-46bd-a9a8-6b9987a9712d]
    ERROR: LoadError: InitError: Error thrown by GAP: Error, Evaluation into
    the closed module `Oscar` breaks incremental compilation because the side
    effects will not be permanent. This is likely due to some other module
    mutating `Oscar` with `eval` during precompilation - don't do this.